Traceback (most recent call last):
  File "/afs/cern.ch/work/h/hinzmann/limit_combination/CMSSW_7_1_5/bin/slc6_amd64_gcc481/combineCards.py", line 46, in <module>
    file = open(fname, "r")
IOError: [Errno 2] No such file or directory: 'wwlvj_BulkG_WW_inclusive_c0p2_M2600_el_10_00_HP_unbin.txt'
